### ISSUE TITLE
Implementation error for CAICRL in caicrl_constraint_net.py file

### ISSUE THREAD

**Issue by Usaywook** [Sriram94/ConfidenceAwareICRL#1]
When I implemented `python train_icrl.py ../config/mujuco_BlockedHalfCheetah/train_CAICRL_HCWithPos-v0.yaml -n 5 -s 1
`, I got the following error.
```
Traceback (most recent call last):
  File "train_icrl.py", line 545, in <module>
    train(args)
  File "train_icrl.py", line 427, in train
    current_progress_remaining=current_progress_remaining)
  File "../constraint_models/constraint_net/caicrl_constraint_net.py", line 365, in train_nn
    sum_1 = sum_1 + a_b[:, 0] 
ValueError: operands could not be broadcast together with shapes (10000,) (5000,)
```
How could I solve it?

Moreover, in CAICRLConstraintNet class, beta, and quantile functions are not defined and local variable regularizer_loss is used. 
Is there a stable version?

**Comment by Sriram94** [comment]
Very sorry for the delay in response, I missed the notification. There was a bug introduced in the code refractor that led to this error, which is fixed now. 

I am closing this issue now, feel free to open again if required.
